export const mockMenu = {
  activeBranch: false,
  activeNode: false,
  blogNode: false,
  categoryId: null,
  children: [
    {
      activeBranch: false,
      activeNode: false,
      blogNode: false,
      categoryId: null,
      children: [
        {
          activeBranch: false,
          activeNode: false,
          blogNode: true,
          categoryId: 3,
          children: [
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [
                {
                  activeBranch: false,
                  activeNode: false,
                  blogNode: true,
                  categoryId: 3,
                  children: [],
                  contentGroupId: 92043358884,
                  contentType: "blog",
                  errorMessage: null,
                  guid: null,
                  isDeleted: false,
                  isNonLinkingNode: false,
                  isPublished: true,
                  label: "Sub-menu Item",
                  level: 4,
                  linkTarget: null,
                  live: true,
                  nodeType: 1,
                  pageId: null,
                  pageTitle: "General Blog",
                  parentGuid: null,
                  slug: "blog",
                  state: "PUBLISHED",
                  subcategory: null,
                  topLevelAncestorGuid: null,
                  url: "http://22628452.hs-sites.com/blog",
                  urlParamStr: "",
                  urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
                },
                {
                  activeBranch: false,
                  activeNode: false,
                  blogNode: true,
                  categoryId: 3,
                  children: [],
                  contentGroupId: 92043358884,
                  contentType: "blog",
                  errorMessage: null,
                  guid: null,
                  isDeleted: false,
                  isNonLinkingNode: false,
                  isPublished: true,
                  label: "Sub-menu Item",
                  level: 4,
                  linkTarget: null,
                  live: true,
                  nodeType: 1,
                  pageId: null,
                  pageTitle: "General Blog",
                  parentGuid: null,
                  slug: "blog",
                  state: "PUBLISHED",
                  subcategory: null,
                  topLevelAncestorGuid: null,
                  url: "http://22628452.hs-sites.com/blog",
                  urlParamStr: "",
                  urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
                },
                {
                  activeBranch: false,
                  activeNode: false,
                  blogNode: true,
                  categoryId: 3,
                  children: [],
                  contentGroupId: 92043358884,
                  contentType: "blog",
                  errorMessage: null,
                  guid: null,
                  isDeleted: false,
                  isNonLinkingNode: false,
                  isPublished: true,
                  label: "Sub-menu Item",
                  level: 4,
                  linkTarget: null,
                  live: true,
                  nodeType: 1,
                  pageId: null,
                  pageTitle: "General Blog",
                  parentGuid: null,
                  slug: "blog",
                  state: "PUBLISHED",
                  subcategory: null,
                  topLevelAncestorGuid: null,
                  url: "http://22628452.hs-sites.com/blog",
                  urlParamStr: "",
                  urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
                },
                {
                  activeBranch: false,
                  activeNode: false,
                  blogNode: true,
                  categoryId: 3,
                  children: [],
                  contentGroupId: 92043358884,
                  contentType: "blog",
                  errorMessage: null,
                  guid: null,
                  isDeleted: false,
                  isNonLinkingNode: false,
                  isPublished: true,
                  label: "Sub-menu Item",
                  level: 4,
                  linkTarget: null,
                  live: true,
                  nodeType: 1,
                  pageId: null,
                  pageTitle: "General Blog",
                  parentGuid: null,
                  slug: "blog",
                  state: "PUBLISHED",
                  subcategory: null,
                  topLevelAncestorGuid: null,
                  url: "http://22628452.hs-sites.com/blog",
                  urlParamStr: "",
                  urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
                },
              ],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Our Services",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/blog",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
            },
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [
                {
                  activeBranch: false,
                  activeNode: false,
                  blogNode: true,
                  categoryId: 3,
                  children: [],
                  contentGroupId: 92043358884,
                  contentType: "blog",
                  errorMessage: null,
                  guid: null,
                  isDeleted: false,
                  isNonLinkingNode: false,
                  isPublished: true,
                  label: "Sub-menu Item",
                  level: 4,
                  linkTarget: null,
                  live: true,
                  nodeType: 1,
                  pageId: null,
                  pageTitle: "General Blog",
                  parentGuid: null,
                  slug: "blog",
                  state: "PUBLISHED",
                  subcategory: null,
                  topLevelAncestorGuid: null,
                  url: "http://22628452.hs-sites.com/blog",
                  urlParamStr: "",
                  urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
                },
                {
                  activeBranch: false,
                  activeNode: false,
                  blogNode: true,
                  categoryId: 3,
                  children: [],
                  contentGroupId: 92043358884,
                  contentType: "blog",
                  errorMessage: null,
                  guid: null,
                  isDeleted: false,
                  isNonLinkingNode: false,
                  isPublished: true,
                  label: "Sub-menu Item",
                  level: 4,
                  linkTarget: null,
                  live: true,
                  nodeType: 1,
                  pageId: null,
                  pageTitle: "General Blog",
                  parentGuid: null,
                  slug: "blog",
                  state: "PUBLISHED",
                  subcategory: null,
                  topLevelAncestorGuid: null,
                  url: "http://22628452.hs-sites.com/blog",
                  urlParamStr: "",
                  urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
                },
                {
                  activeBranch: false,
                  activeNode: false,
                  blogNode: true,
                  categoryId: 3,
                  children: [],
                  contentGroupId: 92043358884,
                  contentType: "blog",
                  errorMessage: null,
                  guid: null,
                  isDeleted: false,
                  isNonLinkingNode: false,
                  isPublished: true,
                  label: "Sub-menu Item",
                  level: 4,
                  linkTarget: null,
                  live: true,
                  nodeType: 1,
                  pageId: null,
                  pageTitle: "General Blog",
                  parentGuid: null,
                  slug: "blog",
                  state: "PUBLISHED",
                  subcategory: null,
                  topLevelAncestorGuid: null,
                  url: "http://22628452.hs-sites.com/blog",
                  urlParamStr: "",
                  urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
                },
                {
                  activeBranch: false,
                  activeNode: false,
                  blogNode: true,
                  categoryId: 3,
                  children: [],
                  contentGroupId: 92043358884,
                  contentType: "blog",
                  errorMessage: null,
                  guid: null,
                  isDeleted: false,
                  isNonLinkingNode: false,
                  isPublished: true,
                  label: "Sub-menu Item",
                  level: 4,
                  linkTarget: null,
                  live: true,
                  nodeType: 1,
                  pageId: null,
                  pageTitle: "General Blog",
                  parentGuid: null,
                  slug: "blog",
                  state: "PUBLISHED",
                  subcategory: null,
                  topLevelAncestorGuid: null,
                  url: "http://22628452.hs-sites.com/blog",
                  urlParamStr: "",
                  urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
                },
              ],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Sub-menu Item",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/blog",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
            },
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Sub-menu Item",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/blog",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
            },
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Sub-menu Item",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/blog",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
            },
          ],
          contentGroupId: 92043358884,
          contentType: "blog",
          errorMessage: null,
          guid: null,
          isDeleted: false,
          isNonLinkingNode: false,
          isPublished: true,
          label: "Main Menu Link",
          level: 2,
          linkTarget: null,
          live: true,
          nodeType: 1,
          pageId: null,
          pageTitle: "General Blog",
          parentGuid: null,
          slug: "blog",
          state: "PUBLISHED",
          subcategory: null,
          topLevelAncestorGuid: null,
          url: "http://22628452.hs-sites.com/blog",
          urlParamStr: "",
          urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
        },
        {
          activeBranch: false,
          activeNode: false,
          blogNode: true,
          categoryId: 3,
          children: [
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Sub-menu Item",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/blog",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
            },
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Sub-menu Item",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/blog",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
            },
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Sub-menu Item",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/blog",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
            },
          ],
          contentGroupId: 92043358884,
          contentType: "blog",
          errorMessage: null,
          guid: null,
          isDeleted: false,
          isNonLinkingNode: false,
          isPublished: true,
          label: "Menu Small",
          level: 2,
          linkTarget: null,
          live: true,
          nodeType: 1,
          pageId: null,
          pageTitle: "General Blog",
          parentGuid: null,
          slug: "blog",
          state: "PUBLISHED",
          subcategory: null,
          topLevelAncestorGuid: null,
          url: "http://22628452.hs-sites.com/blog",
          urlParamStr: "",
          urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
        },
        {
          activeBranch: false,
          activeNode: false,
          blogNode: true,
          categoryId: 3,
          children: [
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [
                {
                  activeBranch: false,
                  activeNode: false,
                  blogNode: true,
                  categoryId: 3,
                  children: [],
                  contentGroupId: 92043358884,
                  contentType: "blog",
                  errorMessage: null,
                  guid: null,
                  isDeleted: false,
                  isNonLinkingNode: false,
                  isPublished: true,
                  label: "Sub-menu Item",
                  level: 4,
                  linkTarget: null,
                  live: true,
                  nodeType: 1,
                  pageId: null,
                  pageTitle: "General Blog",
                  parentGuid: null,
                  slug: "blog",
                  state: "PUBLISHED",
                  subcategory: null,
                  topLevelAncestorGuid: null,
                  url: "http://22628452.hs-sites.com/blog",
                  urlParamStr: "",
                  urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
                },
              ],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Sub-menu Item",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/blog",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
            },
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Sub-menu Item",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/blog",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
            },
          ],
          contentGroupId: 92043358884,
          contentType: "blog",
          errorMessage: null,
          guid: null,
          isDeleted: false,
          isNonLinkingNode: false,
          isPublished: true,
          label: "Main Menu Link",
          level: 2,
          linkTarget: null,
          live: true,
          nodeType: 1,
          pageId: null,
          pageTitle: "General Blog",
          parentGuid: null,
          slug: "blog",
          state: "PUBLISHED",
          subcategory: null,
          topLevelAncestorGuid: null,
          url: "http://22628452.hs-sites.com/blog",
          urlParamStr: "",
          urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
        },
      ],
      contentGroupId: null,
      contentType: null,
      errorMessage: null,
      guid: null,
      isDeleted: false,
      isNonLinkingNode: false,
      isPublished: true,
      label: "Lorem Ipsum",
      level: 1,
      linkTarget: null,
      live: true,
      nodeType: 3,
      pageId: null,
      pageTitle: null,
      parentGuid: null,
      slug: null,
      state: null,
      subcategory: null,
      topLevelAncestorGuid: null,
      url: "",
      urlParamStr: "",
      urlWithoutAnchor: "",
    },
    {
      activeBranch: false,
      activeNode: false,
      blogNode: false,
      categoryId: null,
      children: [
        {
          activeBranch: false,
          activeNode: false,
          blogNode: true,
          categoryId: 3,
          children: [
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Sub-menu Item - Longer",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/blog",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
            },
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Sub-short",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/blog",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
            },
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Sub-menu Item",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/blog",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
            },
          ],
          contentGroupId: 92043358884,
          contentType: "blog",
          errorMessage: null,
          guid: null,
          isDeleted: false,
          isNonLinkingNode: false,
          isPublished: true,
          label: "Main Menu Link - Longer",
          level: 2,
          linkTarget: null,
          live: true,
          nodeType: 1,
          pageId: null,
          pageTitle: "General Blog",
          parentGuid: null,
          slug: "blog",
          state: "PUBLISHED",
          subcategory: null,
          topLevelAncestorGuid: null,
          url: "http://22628452.hs-sites.com/blog",
          urlParamStr: "",
          urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
        },
        {
          activeBranch: false,
          activeNode: false,
          blogNode: true,
          categoryId: 3,
          children: [
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Sub-menu Item",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/blog",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
            },
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Sub-menu Item",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/blog",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
            },
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Sub-menu Item",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/blog",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
            },
          ],
          contentGroupId: 92043358884,
          contentType: "blog",
          errorMessage: null,
          guid: null,
          isDeleted: false,
          isNonLinkingNode: false,
          isPublished: true,
          label: "Menu Small",
          level: 2,
          linkTarget: null,
          live: true,
          nodeType: 1,
          pageId: null,
          pageTitle: "General Blog",
          parentGuid: null,
          slug: "blog",
          state: "PUBLISHED",
          subcategory: null,
          topLevelAncestorGuid: null,
          url: "http://22628452.hs-sites.com/blog",
          urlParamStr: "",
          urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
        },
        {
          activeBranch: false,
          activeNode: false,
          blogNode: true,
          categoryId: 3,
          children: [
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [
                {
                  activeBranch: false,
                  activeNode: false,
                  blogNode: true,
                  categoryId: 3,
                  children: [],
                  contentGroupId: 92043358884,
                  contentType: "blog",
                  errorMessage: null,
                  guid: null,
                  isDeleted: false,
                  isNonLinkingNode: false,
                  isPublished: true,
                  label: "Sub-menu Item",
                  level: 4,
                  linkTarget: null,
                  live: true,
                  nodeType: 1,
                  pageId: null,
                  pageTitle: "General Blog",
                  parentGuid: null,
                  slug: "blog",
                  state: "PUBLISHED",
                  subcategory: null,
                  topLevelAncestorGuid: null,
                  url: "http://22628452.hs-sites.com/blog",
                  urlParamStr: "",
                  urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
                },
              ],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Sub-menu Item",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/blog",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
            },
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Sub-menu Item",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/blog",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
            },
          ],
          contentGroupId: 92043358884,
          contentType: "blog",
          errorMessage: null,
          guid: null,
          isDeleted: false,
          isNonLinkingNode: false,
          isPublished: true,
          label: "Main Menu Link",
          level: 2,
          linkTarget: null,
          live: true,
          nodeType: 1,
          pageId: null,
          pageTitle: "General Blog",
          parentGuid: null,
          slug: "blog",
          state: "PUBLISHED",
          subcategory: null,
          topLevelAncestorGuid: null,
          url: "http://22628452.hs-sites.com/blog",
          urlParamStr: "",
          urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
        },
      ],
      contentGroupId: null,
      contentType: null,
      errorMessage: null,
      guid: null,
      isDeleted: false,
      isNonLinkingNode: false,
      isPublished: true,
      label: "Lorem Ipsum",
      level: 1,
      linkTarget: null,
      live: true,
      nodeType: 3,
      pageId: null,
      pageTitle: null,
      parentGuid: null,
      slug: null,
      state: null,
      subcategory: null,
      topLevelAncestorGuid: null,
      url: "",
      urlParamStr: "",
      urlWithoutAnchor: "",
    },
    {
      activeBranch: false,
      activeNode: false,
      blogNode: false,
      categoryId: null,
      children: [
        {
          activeBranch: false,
          activeNode: false,
          blogNode: true,
          categoryId: 3,
          children: [
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Sub-menu Item - Longer",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/blog",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
            },
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Sub-short",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/blog",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
            },
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Sub-menu Item",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/blog",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
            },
          ],
          contentGroupId: 92043358884,
          contentType: "blog",
          errorMessage: null,
          guid: null,
          isDeleted: false,
          isNonLinkingNode: false,
          isPublished: true,
          label: "Main Menu Link - Longer",
          level: 2,
          linkTarget: null,
          live: true,
          nodeType: 1,
          pageId: null,
          pageTitle: "General Blog",
          parentGuid: null,
          slug: "blog",
          state: "PUBLISHED",
          subcategory: null,
          topLevelAncestorGuid: null,
          url: "http://22628452.hs-sites.com/blog",
          urlParamStr: "",
          urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
        },
        {
          activeBranch: false,
          activeNode: false,
          blogNode: true,
          categoryId: 3,
          children: [
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Sub-menu Item",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/blog",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
            },
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Sub-menu Item",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/blog",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
            },
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Sub-menu Item",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/blog",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
            },
          ],
          contentGroupId: 92043358884,
          contentType: "blog",
          errorMessage: null,
          guid: null,
          isDeleted: false,
          isNonLinkingNode: false,
          isPublished: true,
          label: "Menu Small",
          level: 2,
          linkTarget: null,
          live: true,
          nodeType: 1,
          pageId: null,
          pageTitle: "General Blog",
          parentGuid: null,
          slug: "blog",
          state: "PUBLISHED",
          subcategory: null,
          topLevelAncestorGuid: null,
          url: "http://22628452.hs-sites.com/blog",
          urlParamStr: "",
          urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
        },
        {
          activeBranch: false,
          activeNode: false,
          blogNode: true,
          categoryId: 3,
          children: [
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [
                {
                  activeBranch: false,
                  activeNode: false,
                  blogNode: true,
                  categoryId: 3,
                  children: [],
                  contentGroupId: 92043358884,
                  contentType: "blog",
                  errorMessage: null,
                  guid: null,
                  isDeleted: false,
                  isNonLinkingNode: false,
                  isPublished: true,
                  label: "Sub-menu Item",
                  level: 4,
                  linkTarget: null,
                  live: true,
                  nodeType: 1,
                  pageId: null,
                  pageTitle: "General Blog",
                  parentGuid: null,
                  slug: "blog",
                  state: "PUBLISHED",
                  subcategory: null,
                  topLevelAncestorGuid: null,
                  url: "http://22628452.hs-sites.com/blog",
                  urlParamStr: "",
                  urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
                },
              ],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Sub-menu Item",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/blog",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
            },
            {
              activeBranch: false,
              activeNode: false,
              blogNode: true,
              categoryId: 3,
              children: [],
              contentGroupId: 92043358884,
              contentType: "blog",
              errorMessage: null,
              guid: null,
              isDeleted: false,
              isNonLinkingNode: false,
              isPublished: true,
              label: "Sub-menu Item",
              level: 3,
              linkTarget: null,
              live: true,
              nodeType: 1,
              pageId: null,
              pageTitle: "General Blog",
              parentGuid: null,
              slug: "blog",
              state: "PUBLISHED",
              subcategory: null,
              topLevelAncestorGuid: null,
              url: "http://22628452.hs-sites.com/blog",
              urlParamStr: "",
              urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
            },
          ],
          contentGroupId: 92043358884,
          contentType: "blog",
          errorMessage: null,
          guid: null,
          isDeleted: false,
          isNonLinkingNode: false,
          isPublished: true,
          label: "Main Menu Link",
          level: 2,
          linkTarget: null,
          live: true,
          nodeType: 1,
          pageId: null,
          pageTitle: "General Blog",
          parentGuid: null,
          slug: "blog",
          state: "PUBLISHED",
          subcategory: null,
          topLevelAncestorGuid: null,
          url: "http://22628452.hs-sites.com/blog",
          urlParamStr: "",
          urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
        },
      ],
      contentGroupId: null,
      contentType: null,
      errorMessage: null,
      guid: null,
      isDeleted: false,
      isNonLinkingNode: false,
      isPublished: true,
      label: "Lorem Ipsum",
      level: 1,
      linkTarget: null,
      live: true,
      nodeType: 3,
      pageId: null,
      pageTitle: null,
      parentGuid: null,
      slug: null,
      state: null,
      subcategory: null,
      topLevelAncestorGuid: null,
      url: "",
      urlParamStr: "",
      urlWithoutAnchor: "",
    },
    {
      activeBranch: false,
      activeNode: false,
      blogNode: true,
      categoryId: 3,
      children: [],
      contentGroupId: 92043358884,
      contentType: "blog",
      errorMessage: null,
      guid: null,
      isDeleted: false,
      isNonLinkingNode: false,
      isPublished: true,
      label: "Patient Advocacy",
      level: 1,
      linkTarget: null,
      live: true,
      nodeType: 1,
      pageId: null,
      pageTitle: "General Blog",
      parentGuid: null,
      slug: "blog",
      state: "PUBLISHED",
      subcategory: null,
      topLevelAncestorGuid: null,
      url: "http://22628452.hs-sites.com/blog",
      urlParamStr: "",
      urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
    },
    {
      activeBranch: false,
      activeNode: false,
      blogNode: true,
      categoryId: 3,
      children: [],
      contentGroupId: 92043358884,
      contentType: "blog",
      errorMessage: null,
      guid: null,
      isDeleted: false,
      isNonLinkingNode: false,
      isPublished: true,
      label: "Investors",
      level: 1,
      linkTarget: null,
      live: true,
      nodeType: 1,
      pageId: null,
      pageTitle: "General Blog",
      parentGuid: null,
      slug: "blog",
      state: "PUBLISHED",
      subcategory: null,
      topLevelAncestorGuid: null,
      url: "http://22628452.hs-sites.com/blog",
      urlParamStr: "",
      urlWithoutAnchor: "http://22628452.hs-sites.com/blog",
    },
  ],
  contentGroupId: null,
  contentType: null,
  errorMessage: null,
  guid: null,
  isDeleted: false,
  isNonLinkingNode: false,
  isPublished: true,
  label: null,
  level: 0,
  linkTarget: null,
  live: true,
  nodeType: 3,
  pageId: null,
  pageTitle: null,
  parentGuid: null,
  slug: null,
  state: null,
  subcategory: null,
  topLevelAncestorGuid: null,
  url: null,
  urlParamStr: "",
  urlWithoutAnchor: "null",
};
