export const mockMenu = {
  activeBranch: false,
  activeNode: false,
  blogNode: false,
  categoryId: null,
  children: [
    {
      activeBranch: false,
      activeNode: false,
      blogNode: false,
      categoryId: null,
      children: [],
      contentGroupId: 1,
      contentType: "page",
      errorMessage: null,
      guid: null,
      isDeleted: false,
      isNonLinkingNode: false,
      isPublished: true,
      label: "Home",
      level: 1,
      linkTarget: null,
      live: true,
      nodeType: 1,
      pageId: null,
      pageTitle: "Home",
      parentGuid: null,
      slug: "home",
      state: null,
      subcategory: null,
      topLevelAncestorGuid: null,
      url: "/home",
      urlParamStr: "",
      urlWithoutAnchor: "/home",
    },
    {
      activeBranch: false,
      activeNode: false,
      blogNode: false,
      categoryId: null,
      children: [
        {
          activeBranch: false,
          activeNode: false,
          blogNode: false,
          categoryId: null,
          children: [],
          contentGroupId: 2,
          contentType: "page",
          errorMessage: null,
          guid: null,
          isDeleted: false,
          isNonLinkingNode: false,
          isPublished: true,
          label: "Excavation",
          level: 2,
          linkTarget: null,
          live: true,
          nodeType: 1,
          pageId: null,
          pageTitle: "Excavation",
          parentGuid: null,
          slug: "excavation",
          state: null,
          subcategory: null,
          topLevelAncestorGuid: null,
          url: "/services/excavation",
          urlParamStr: "",
          urlWithoutAnchor: "/services/excavation",
        },
        {
          activeBranch: false,
          activeNode: false,
          blogNode: false,
          categoryId: null,
          children: [],
          contentGroupId: 3,
          contentType: "page",
          errorMessage: null,
          guid: null,
          isDeleted: false,
          isNonLinkingNode: false,
          isPublished: true,
          label: "Site Preparation",
          level: 2,
          linkTarget: null,
          live: true,
          nodeType: 1,
          pageId: null,
          pageTitle: "Site Preparation",
          parentGuid: null,
          slug: "site-preparation",
          state: null,
          subcategory: null,
          topLevelAncestorGuid: null,
          url: "/services/site-preparation",
          urlParamStr: "",
          urlWithoutAnchor: "/services/site-preparation",
        },
        {
          activeBranch: false,
          activeNode: false,
          blogNode: false,
          categoryId: null,
          children: [],
          contentGroupId: 4,
          contentType: "page",
          errorMessage: null,
          guid: null,
          isDeleted: false,
          isNonLinkingNode: false,
          isPublished: true,
          label: "Demolition",
          level: 2,
          linkTarget: null,
          live: true,
          nodeType: 1,
          pageId: null,
          pageTitle: "Demolition",
          parentGuid: null,
          slug: "demolition",
          state: null,
          subcategory: null,
          topLevelAncestorGuid: null,
          url: "/services/demolition",
          urlParamStr: "",
          urlWithoutAnchor: "/services/demolition",
        },
      ],
      contentGroupId: 5,
      contentType: "page",
      errorMessage: null,
      guid: null,
      isDeleted: false,
      isNonLinkingNode: false,
      isPublished: true,
      label: "Services",
      level: 1,
      linkTarget: null,
      live: true,
      nodeType: 1,
      pageId: null,
      pageTitle: "Services",
      parentGuid: null,
      slug: "services",
      state: null,
      subcategory: null,
      topLevelAncestorGuid: null,
      url: "/services",
      urlParamStr: "",
      urlWithoutAnchor: "/services",
    },
    {
      activeBranch: false,
      activeNode: false,
      blogNode: false,
      categoryId: null,
      children: [
        {
          activeBranch: false,
          activeNode: false,
          blogNode: false,
          categoryId: null,
          children: [],
          contentGroupId: 6,
          contentType: "page",
          errorMessage: null,
          guid: null,
          isDeleted: false,
          isNonLinkingNode: false,
          isPublished: true,
          label: "Residential Projects",
          level: 2,
          linkTarget: null,
          live: true,
          nodeType: 1,
          pageId: null,
          pageTitle: "Residential Projects",
          parentGuid: null,
          slug: "residential-projects",
          state: null,
          subcategory: null,
          topLevelAncestorGuid: null,
          url: "/projects/residential-projects",
          urlParamStr: "",
          urlWithoutAnchor: "/projects/residential-projects",
        },
      ],
      contentGroupId: 7,
      contentType: "page",
      errorMessage: null,
      guid: null,
      isDeleted: false,
      isNonLinkingNode: false,
      isPublished: true,
      label: "Projects",
      level: 1,
      linkTarget: null,
      live: true,
      nodeType: 1,
      pageId: null,
      pageTitle: "Projects",
      parentGuid: null,
      slug: "projects",
      state: null,
      subcategory: null,
      topLevelAncestorGuid: null,
      url: "/projects",
      urlParamStr: "",
      urlWithoutAnchor: "/projects",
    },
    {
      activeBranch: false,
      activeNode: false,
      blogNode: false,
      categoryId: null,
      children: [],
      contentGroupId: 8,
      contentType: "page",
      errorMessage: null,
      guid: null,
      isDeleted: false,
      isNonLinkingNode: false,
      isPublished: true,
      label: "About Us",
      level: 1,
      linkTarget: null,
      live: true,
      nodeType: 1,
      pageId: null,
      pageTitle: "About Us",
      parentGuid: null,
      slug: "about-us",
      state: null,
      subcategory: null,
      topLevelAncestorGuid: null,
      url: "/about-us",
      urlParamStr: "",
      urlWithoutAnchor: "/about-us",
    },
    {
      activeBranch: false,
      activeNode: false,
      blogNode: false,
      categoryId: null,
      children: [],
      contentGroupId: 9,
      contentType: "page",
      errorMessage: null,
      guid: null,
      isDeleted: false,
      isNonLinkingNode: false,
      isPublished: true,
      label: "Contact",
      level: 1,
      linkTarget: null,
      live: true,
      nodeType: 1,
      pageId: null,
      pageTitle: "Contact",
      parentGuid: null,
      slug: "contact",
      state: null,
      subcategory: null,
      topLevelAncestorGuid: null,
      url: "/contact",
      urlParamStr: "",
      urlWithoutAnchor: "/contact",
    },
  ],
};
